

class StackExchangeColumns:
    id = "Id"
    post_type_id = "PostTypeId"
    accepted_answer_id = "AcceptedAnswerId"
    parent_id = "ParentId"
    creation_date = "CreationDate"
    deletion_date = "DeletionDate"
    score = "Score"
    view_count = "ViewCount"
    body = "Body"
    owner_user_id = "OwnerUserId"
    owner_display_name = "OwnerDisplayName"
    last_editor_user_id = "LastEditorUserId"
    last_editor_display_name = "LastEditorDisplayName"
    last_edit_date = "LastEditDate"
    last_activity_date = "LastActivityDate"
    title = "Title"
    tags = "Tags"
    answer_count = "AnswerCount"
    comment_count = "CommentCount"
    favorite_count = "FavoriteCount"
    closed_date = "ClosedDate"
    community_owned_date = "CommunityOwnedDate"
    content_license = "ContentLicense"
    post_id = "PostId"
    text = "Text"
    user_display_name = "UserDisplayName"
    user_id = "UserId"
    source_tag_name = "SourceTagName"
    target_tag_name = "TargetTagName"
    auto_rename_count = "AutoRenameCount"
    last_auto_rename = "LastAutoRename"
    approved_by_user_id = "ApprovedByUserId"
    approval_date = "ApprovalDate"
    tag_name = "TagName"
    count = "Count"
    excerpt_post_id = "ExcerptPostId"
    wiki_post_id = "WikiPostId"
    is_moderator_only = "IsModeratorOnly"
    is_required = "IsRequired"

    tag = "Tag"
    date = "Date"
    tag_id = "TagId"
